# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.  category: Network
description: An executable used to update cloudflare DNS entries with the current machine's external IP addresss.
executables:
  constanze:
    dependencies:
    - base
    - constanze
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: callummance/constanze
library:
  dependencies:
  - base
  - aeson
  - bytestring
  - cmdargs
  - dns
  - lens
  - lens-aeson
  - iproute
  - text
  - wreq
  source-dirs: library
license: MIT
maintainer: Callum Mance
name: constanze
synopsis: A new Haskeleton package.
tests:
  constanze-test-suite:
    dependencies:
    - base
    - constanze
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.1'
